# -*- coding: utf-8 -*-
"""Numpy(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyoOD2MZnPqGebF31M3ZmM0NEpbYUOk2

#**Numpy Attribute**
"""

import numpy as np

np.identity(3)

a1 = np.arange(10)                              #vector
a2 = np.arange(12,dtype = float).reshape(3,4)   #matrix
a3 = np.arange(8).reshape(2,2,2)                #3D Array

a1.ndim #1
a2.ndim #2
a3.ndim #2

a1.shape    #(10,)
a2.shape    #(3, 4)
a3.shape    #(2, 2, 2)

#size
print(a3.size)
a3

#itemsize
a1.itemsize  #give the size of byte that use in array

#dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

"""
##change datatype"""

#astype
print(a3.astype(np.int32))

"""##Array operations"""

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

#scalar Operation

#arithmetic
a1 *2 #use any arithmetic operation here

#relational

a2 == 20

# vector operation
print(a1)
print(a2)
#arithemetic
a1 * a2

#realational
a1 == a2

"""##array functions

"""

a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)

a1

#min/max/prod/sum

print(np.min(a1),"\n",  #smallest number
np.max(a1),"\n",        #biggest number
np.sum(a1),"\n",        #sum of all numbers
np.prod(a1))            #maltipliation of all numbers


np.max(a1,axis=1) #row wise
np.max(a1,axis=0) #column wise

#mean/median/var/std
np.std(a1,axis = 1)

#trignomatric function
np.sin(a1)

#Dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

#log and exponents

np.exp(a1)
np.log(a1)

# round / floor /  ceil
print(np.random.random((2,3))*100)
print(np.floor(np.random.random((2,3))*100))
print(np.round(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

"""## Indexing and Slicing"""

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

a2[2][2]

a3

a3[1,1,1]

a1

a1[2:7]

for i in a2:
  print(i)

a2[0:2,1:]

a2[::2,1::2]

a2[1,::3]

a2[:,2]

a2[0:2,2:]



a3 = np.arange(27).reshape(3,3,3)
a3

a3[::2,0,::2]

a3

for i in np.nditer(a3):
  print(i)

"""##Reshaping"""

#reshape

#Transpose
np.transpose(a2)
a2.T

#ravel
np.ravel(a2)

"""##Stacking"""

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

#Horizonatal
np.hstack((a4,a5))

#Vartical
np.vstack((a4,a5))

"""##Spiliting"""

#Horizontal
print(a4)
np.hsplit(a4,2)

#vartical
print(a5)
np.vsplit(a5,3)